# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerId: varunpatel01
  imageName: aristotle

steps: 
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    sonarQubeRunAnalysis: false

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'varunpatel01/aristotle'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'azure-pipeline'

- task: Docker@2
  inputs:
    containerRegistry: 'Azure CR'
    repository: 'aristotle'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'